import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import SignOutButton from "@/components/SignOutButton";
import { Header } from "antd/es/layout/layout";
import { Layout } from "antd";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "User Management Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Layout>
          <Header className="flex justify-between items-center h-40 px-6 bg-gray-800 shadow-md">
          <div className="text-2xl font-bold text-white">User Management Platform</div>
          <SignOutButton />
        </Header>

          <main className="h-full w-full overflow-y-auto">
            {children}
          </main>
          </Layout>
        </Providers>
      </body>
    </html>
  );
}